FROM scratch
COPY docker/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY docker/bridge /bridge
EXPOSE 39281
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 CMD ["/bridge", "--healthcheck"]
ENTRYPOINT ["/bridge"]
